apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-vault-secret
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-secret
  template:
    metadata:
      labels:
        app: vault-secret
    spec:
      containers:
      - name: my-container
        image: busybox
        command:
        - "/bin/sh"
        - "-c"
        - |
          while true; do
            echo Username: $USERNAME && echo Password: $PASSWORD && echo Token: $TOKEN
            sleep 1
          done
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: password
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: token