apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: development
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: development
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"] 
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-reader
  namespace: development
subjects:
  - kind: ServiceAccount
    name: pod-reader
    namespace: development
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name:  pod-reader-token
  namespace: development
  annotations:
    kubernetes.io/service-account.name:  pod-reader
type: kubernetes.io/service-account-token
