apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-secret
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: busybox
        command:
        - "/bin/sh"
        - "-c"
        - |
          while true; do
            echo Username: $USERNAME && echo Password: $PASSWORD
            sleep 1
          done
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: dev-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-secret
              key: password
